const ContentType = {
  APPLICATION_JSON: 0,
  APPLICATION_OCTET_STREAM: 10,
  APPLICATION_BASE64: 20,
  APPLICATION_XML: 30,
  AUDIO_MPEG: 40,
  AUDIO_OGG: 50,
  AUDIO: 60,
  VIDEO_MP4: 70,
  TEXT_PLAIN: 80,
  TEXT_HTML: 90,
  IMAGE_JPEG: 100,
  IMAGE_PNG: 110
};

export default ContentType;
